name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/easymart:latest .

      - name: Push Image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/easymart:latest

      - name: Deploy to VM2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker stop easymart || true
            docker rm easymart || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/easymart:latest
            docker run -d -p 3000:3000 --name easymart ${{ secrets.DOCKERHUB_USERNAME }}/easymart:latest
